### ISSUE TITLE
Do not go to count "lateness" time

### ISSUE THREAD

**Issue by Satont** [AlexWayfer/stream_timer#19]
I'd like stop ticks of timer, if time of timer is passed.

I mean if i set 5 minutes in timer settings, and when 5 minutes gone, then do nothing, instead of count lateness.

**Comment by AlexWayfer** [comment]
Why? For what, for example?

**Comment by Satont** [comment]
Example usage:

Timer for stream start with text `starting in 05:00 minutes`, when time is over show `starting soon`

**Comment by AlexWayfer** [comment]
Nice example, thanks.

So, there is should be lateness (countup) text, but without time.

I'll think about it.
